var annotated_dup =
[
    [ "AccountManager", "class_account_manager.html", "class_account_manager" ],
    [ "AccountsWindow", "class_accounts_window.html", "class_accounts_window" ],
    [ "Bank", "class_bank.html", "class_bank" ],
    [ "BankAccount", "class_bank_account.html", "class_bank_account" ],
    [ "Calculator", "class_calculator.html", "class_calculator" ],
    [ "Client", "class_client.html", "class_client" ],
    [ "ClientManager", "class_client_manager.html", "class_client_manager" ],
    [ "Credit", "class_credit.html", "class_credit" ],
    [ "CreditCalculator", "class_credit_calculator.html", "class_credit_calculator" ],
    [ "creditCalculatorWindow", "classcredit_calculator_window.html", "classcredit_calculator_window" ],
    [ "CreditSchedule", "class_credit_schedule.html", "class_credit_schedule" ],
    [ "EmailSender", "class_email_sender.html", "class_email_sender" ],
    [ "InterestCalculator", "class_interest_calculator.html", "class_interest_calculator" ],
    [ "InTransaction", "class_in_transaction.html", "class_in_transaction" ],
    [ "Login", "class_login.html", "class_login" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "MyCreditWindow", "class_my_credit_window.html", "class_my_credit_window" ],
    [ "MyDataWindow", "class_my_data_window.html", "class_my_data_window" ],
    [ "NewAccountWindow", "class_new_account_window.html", "class_new_account_window" ],
    [ "OutTransaction", "class_out_transaction.html", "class_out_transaction" ],
    [ "Payment", "class_payment.html", "class_payment" ],
    [ "Registration", "class_registration.html", "class_registration" ],
    [ "SavingsAccount", "class_savings_account.html", "class_savings_account" ],
    [ "StatisticsWindow", "class_statistics_window.html", "class_statistics_window" ],
    [ "Transaction", "class_transaction.html", "class_transaction" ],
    [ "TransactionWindow", "class_transaction_window.html", "class_transaction_window" ],
    [ "verifyPINWindow", "classverify_p_i_n_window.html", "classverify_p_i_n_window" ],
    [ "WitdrawalWindow", "class_witdrawal_window.html", "class_witdrawal_window" ]
];